### ISSUE TITLE
vcsstore, vcsclient: Are annotated tags supported?

### ISSUE THREAD

**Issue by shurcooL** [sourcegraph/vcsstore#11]
I can't tell if I'm using this package incorrectly, or if it doesn't support annotated tags in an expected way.

Consider the `github.com/azul3d/audio` git repo. It has an annotated tag `v1` which is `f8d048baeca3571b825c647ce6bdc59f9fbf004f`.

If I do `commitId, err = repo.ResolveTag("v1")`, I get `f8d048baeca3571b825c647ce6bdc59f9fbf004f`.

But if I try to do `repo.FileSystem(commitId)` or even `repo.GetCommit(commitId)`, they both produce errors. As far as I can tell, I need to get the parent commit of the annotated tag, but how can I do that if even `repo.GetCommit(commitId)` fails?

But should I even have to ask for the parent commit of annotated tag, or should the annotated tag work as if it's the parent commit when asking for a `FileSystem`?

**Comment by dmitshur** [comment]
I think I can resolve this issue by now. The question was:

> I can't tell if I'm using this package incorrectly, or if it doesn't support annotated tags in an expected way.

The answer was this package did not support annotated tags (when using old `git2go`-based `git` implementation, it has since been completely replaced by another `go-git`-based `git` implementation).

I'll close this since the actual lower level issue is tracked in https://github.com/sourcegraph/go-vcs/issues/24.
